config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  resources :posts do
    resources :comments
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  validates :comment_body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :post_body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all.order(:id)
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create! comment_params

    redirect_to post_path(@post)
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.update comment_params

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end

  private
  def comment_params
    params.require(:comment).permit(:comment_body)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # Nice! I think you could just do Post.all.reverse and it would work the same since,
  # I believe that later entires will have a higher id :)
  def index
    @posts = Post.all.order(:id).reverse
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create! post_params
    # You could actually just write `@post` for shorten syntax
    redirect_to post_path(@post)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update post_params

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  # nice job defining private post_params!
  private
  def post_params
    params.require(:post).permit(:title, :post_body, :tag)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/edit.html.erb
<div id="back" class="emphasis"><%= link_to "Back to Post", post_path(@post) %></div>

<h2>Edit Comment:</h2>
<%= form_for [@post, @comment] do |f| %>

  <div><%= f.label :comment %></div>
  <div><%= f.text_area :comment_body, :cols => "24", :rows => "4" %></div>

  <div><%= f.submit "Edit" %></div>
<% end %>

app/views/comments/index.html.erb
<h1>Comments <a href="/comments/new">(+)</a></h1>

  <% @comments.each do |comment| %>
      <ul>
        <li>Updated At: <%= comment.updated_at %></li>
        <li><%= comment.comment_body %></li>
        <li>Post ID: <%= comment.post_id %>  </li>
      </ul>
  <% end %>

app/views/comments/new.html.erb
<div id="back" class="emphasis"><%= link_to "Back to Post", post_path(@post) %></div>

<h2>Make a New Comment:</h2>
<%= form_for [@post, @comment] do |f| %>

  <div><%= f.label :comment %></div>
  <div><%= f.text_area :comment_body, :cols => "24", :rows => "4" %></div>

  <div><%= f.submit "Create" %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-beta1/jquery.min.js"></script>
  <title>Scribble</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
  <div class="col-lg-4 col-lg-offset-4" id="appBox">
    <h1 id="scribble">Scribble</h1>
        <%= yield %>
    </div>
  </div>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>
</html>

app/views/posts/edit.html.erb
<div id="back" class="emphasis"><%= link_to "Back to Post", post_path %></div>

<h2>Edit Post</h2>
<%= form_for @post do |f| %>
  <div><%= f.label :title %>
  <%= f.text_field :title %></div>
  </br>
  <div><%= f.label :post %></div>
  <div><%= f.text_area :post_body, :cols => "24", :rows => "4"  %></div>

  <div><%= f.label :tags %>
  <%= f.text_field :tag %></div>

  <div><%= f.submit "Edit" %></div>
<% end %>

app/views/posts/index.html.erb
<h1>Posts <%= link_to "(+)", new_post_path %></h1>

  <% @posts.each do |post| %>
    <span class="emphasis" id="postName"><%= link_to post.title, post %></span>
    <div><span class="emphasis">Updated At: </span><%= post.updated_at %></div>
    <div><%= post.post_body %></div>
    <div><span class="emphasis">Tags: </span><%= post.tag %>  </div>
    </br>
  <% end %>

app/views/posts/new.html.erb
<div id="back" class="emphasis"><%= link_to "Back to Posts", posts_path %></div>

<h2>Make a New Post:</h2>
<%= form_for @post do |f| %>
  <div><%= f.label :title %>
  <%= f.text_field :title %></div>
</br>
  <div><%= f.label :post %></div>
  <div><%= f.text_area :post_body, :cols => "24", :rows => "4"  %></div>

  <div><%= f.label :tags %>
  <%= f.text_field :tag %></div>

  <div><%= f.submit "Create" %></div>
<% end %>

app/views/posts/show.html.erb
<div id="back" class="emphasis"><%= link_to "Back to Posts", posts_path %></div>

<h2><%= @post.title %></h2>
  <div><span class="emphasis">Updated At: </span><%= @post.updated_at %></div>
  <div><%= @post.post_body %></div>
  <div><span class="emphasis">Tags: </span><%= @post.tag %>  </div>
<button class="makeButton"><%= link_to "Edit Post", edit_post_path( @post ) %></button>

<%= form_for @post, method: :delete do |f| %>
  <%= f.submit "Delete Entire Post!", class: "delete" %>
<% end %>

  <h3>Comments <%= link_to "(+)", new_post_comment_url( @post ) %></h3>

      <% @post.comments.each do |comment| %>
        <div><span class="emphasis">Updated At: </span><%= comment.updated_at %></div>
          <div><%= comment.comment_body %></div>
          <div><button class="makeButton"><%= link_to "Edit Comment", edit_post_comment_url( @post, comment ) %></button></div>
          <div><%= form_for [@post, comment], method: :delete do |f| %>
            <%= f.submit "Delete Comment!", class: "delete" %>
          <% end %></div>
      <% end %>


<script>
  // var deleteButton = document.querySelector("form");
  // deleteButton.addEventListener("click", preventDelete);
  //
  // function preventDelete () {
  //   var input = prompt("Are you sure you want to delete this post?\nType 'no' to prevent deletion.");
    // if (input == 'no') {
    //   break
    // }; //HOW TO GET THIS TO WORK?
  // }
</script>